version: '3.8'

services:

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib.postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432

  chat-app:
    build: .
    container_name: chat-app
    command: ./wait-for-postgres.sh db ./chat-app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env